on: [push]

jobs:
  ligo-action:
    runs-on: ubuntu-latest
    name: Test action outputs version of ligo
    steps:
      - name: Ligo version
        uses: marigold-dev/ligo-action@main
        with:
          ligo_version: 0.70.1
          command: version
